### ISSUE TITLE
Problem with disco 

### ISSUE THREAD

**Issue by CyberCosmos24** [elderlabs/BetterDisco#4]
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/src/disco-py/disco/util/emitter.py", line 80, in __call__
    return self.callback(*args, **kwargs)
  File "/root/src/disco-py/disco/bot/bot.py", line 452, in on_message_create
    result = self.handle_message(event.message)
  File "/root/src/disco-py/disco/bot/bot.py", line 444, in handle_message
    if command.plugin.execute(CommandEvent(command, msg, match)):
  File "/root/src/disco-py/disco/bot/command.py", line 55, in __init__
    self.msg = event.message
AttributeError: 'Message' object has no attribute 'message'
2022-03-08T22:24:52Z <Greenlet at 0x7f6e00d70260: <disco.util.emitter.EmitterSubscription object at 0x7f6e00deee20>(<disco.gateway.events.MessageCreate object at 0x7f)> failed with AttributeError
================
Both event.reply() and event.msg.reply() does not work

**Comment by elderlabs** [comment]
Two things:
1. Format your copy/pasta in a codeblock.
2. Don't use staging builds marked "may break things"

I am aware of an issue regarding the change in event replies, however, the feature is incomplete and functions properly on my end. There are still a few bugs to iron out.

I cannot provide further support without some amount of source or details regarding what it is you're looking to do -- especially in instances where you're using builds in staging. While updates to the main branch aren't pushed frequently, they're known to be stable. Using the staging branch is at your own risk. It's best to build your project with a static commit hash rather than depending on whatever the latest push may be.

**Comment by CyberCosmos24** [comment]
What is the main branch I should use then?

**Comment by CyberCosmos24** [comment]
I just want to able to be able to do the ping command listed in your README.md

**Comment by elderlabs** [comment]
That's b1nzy's readme. BDisco isn't advertised as a library that's ready for production with those looking to learn a new library at this time. The main branch is _quite literally_ labeled `main`.

**Comment by CyberCosmos24** [comment]
Okay thank you

**Comment by elderlabs** [comment]
I've corrected the error you noted above, which came about when adding InteractionEvent support to the command handler. A proper error message should appear now.

Proper up-to-date documentation will be available closer to the full release of BDisco.
